kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kasten-role-custom
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - actions.kio.kasten.io
    resources:
      - backupactions
      - backupactions/details
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - actions.kio.kasten.io
    resources:
      - cancelactions
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - actions.kio.kasten.io
    resources:
      - exportactions
      - exportactions/details
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - actions.kio.kasten.io
    resources:
      - importactions
      - importactions/details
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - actions.kio.kasten.io
    resources:
      - reportactions
      - reportactions/details
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - actions.kio.kasten.io
    resources:
      - restoreactions
      - restoreactions/details
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - actions.kio.kasten.io
    resources:
      - validateactions
      - validateactions/details
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - actions.kio.kasten.io
    resources:
      - retireactions
      - retireactions/details
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - actions.kio.kasten.io
    resources:
      - runactions
      - runactions/details
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - actions.kio.kasten.io
    resources:
      - batchrestoreactions
      - batchrestoreactions/details
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - apps.kio.kasten.io
    resources:
      - applications
      - applications/details
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - apps.kio.kasten.io
    resources:
      - restorepoints
      - restorepoints/details
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - apps.kio.kasten.io
    resources:
      - restorepointcontents
      - restorepointcontents/details
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - config.kio.kasten.io
    resources:
      - policies
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - config.kio.kasten.io
    resources:
      - profiles
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups:
      - config.kio.kasten.io
    resources:
      - policy
