apiVersion: v1
kind: Namespace
metadata:
  name: project-1
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-2
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-3
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-4
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-5
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-6
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-7
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-8
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-9
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-10
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-11
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-12
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-13
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-14
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-15
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-16
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-17
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-18
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-19
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-20
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-21
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-22
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-23
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-24
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-25
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-26
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-27
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-28
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-29
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-30
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-31
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-32
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-33
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-34
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-35
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-36
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-37
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-38
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-39
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 

apiVersion: v1
kind: Namespace
metadata:
  name: project-40
  labels:
    k8s.ovn.org/primary-user-defined-network: "" 
