apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: strict-nncp-console-viewer
rules:
- apiGroups:
  - "nmstate.io"
  resources:
  - "nodenetworkconfigurationpolicies"
  verbs:
  - "get"
  - "list"
  - "watch"

- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - "customresourcedefinitions"
  resourceNames:
  - "nodenetworkconfigurationpolicies.nmstate.io" 
  verbs:
  - "get"

- apiGroups:
  - "project.openshift.io"
  resources:
  - "projects"
  verbs:
  - "list"
- apiGroups:
  - "" 
  resources:
  - "namespaces"
  verbs:
  - "list"
- apiGroups:
  - "console.openshift.io"
  resources:
  - "consolelinks"
  verbs:
  - "get"
  - "list"
- apiGroups:
  - "user.openshift.io"
  resources:
  - "users"
  resourceNames:
  - "~"
  verbs:
  - "get"
